# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: '0 Build me inputs'
on:
  workflow_dispatch:
    inputs:
      mapping:
        description: 'mapping'
        required: false
        default: 'default'
      custom_config:
        description: 'custom_config'
        required: false
        default: 'default'
      kconfig:
        description: 'kconfig'
        required: false
        default: 'default'
      branches:
        description: 'branches'
        required: false
        default: 'default'
      modules:
        description: 'modules'
        required: false
        default: 'default'
jobs:
  process-inputs:
    runs-on: ubuntu-latest
    outputs:
      mapping: ${{ steps.process-inputs.outputs.mapping }}
      custom_config: ${{ steps.process-inputs.outputs.custom_config }}
      kconfig: ${{ steps.process-inputs.outputs.kconfig }}
      branches: ${{ steps.process-inputs.outputs.branches }}
      modules: ${{ steps.process-inputs.outputs.modules }}
    steps:
      - name: Process inputs
        id: process-inputs
        run: |
          set-output()
          {
            json=`echo "$2" | jq -cnR 'inputs | split(",";"")'`
            echo "$1=$json" >> $GITHUB_OUTPUT
          }
          set-output "mapping" "${{ github.event.inputs.mapping }}"
          set-output "custom_config" "${{ github.event.inputs.custom_config }}"
          set-output "kconfig" "${{ github.event.inputs.kconfig }}"
          set-output "branches" "${{ github.event.inputs.branches }}"
          set-output "modules" "${{ github.event.inputs.modules }}"
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    needs: process-inputs
    with:
      board: 'nice_nano'
      shield: 'corne_left,corne_right'
      alphas: 'Workman'
      nav: 'default'
      layers: 'default'
      mapping: ${{ needs.process-inputs.outputs.mapping }}
      custom_config: ${{ needs.process-inputs.outputs.custom_config }}
      kconfig: ${{ needs.process-inputs.outputs.kconfig }}
      branches: ${{ needs.process-inputs.outputs.branches }}
      modules: ${{ needs.process-inputs.outputs.modules }}


