# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Inputs'
on:
  workflow_dispatch:
    inputs:
      board:
        description: 'board'
        required: true
      shield:
        description: 'shield'
        required: false
        default: 'default'
      alphas:
        description: 'alphas'
        required: false
        default: 'default'
        type: choice
        options:
        - "default"
        - "AZERTY"
        - "BEAKL15"
        - "Colemak"
        - "ColemakDHK"
        - "Dvorak"
        - "Halmak"
        - "QWERTY"
        - "QWERTZ"
        - "Workman"
      nav:
        description: 'nav'
        required: false
        default: 'default'
        type: choice
        options:
        - "default"
        - "invertedT"
        - "vi"
      layers:
        description: 'layers'
        required: false
        default: 'default'
        type: choice
        options:
        - "default"
        - "flip"
      mapping:
        description: 'mapping'
        required: false
        default: 'default'
      custom_config:
        description: 'custom_config'
        required: false
        default: 'default'
      kconfig:
        description: 'kconfig'
        required: false
        default: 'default'
      branches:
        description: 'branches'
        required: false
        default: 'default'
      modules:
        description: 'modules'
        required: false
        default: 'default'
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: 'nice_nano'
      shield: 'corne_left,corne_right'
      alphas: 'Workman'
      nav: 'default'
      layers: 'default'
      mapping: 'default'
      custom_config: 'default'
      kconfig: 'default'
      branches: 'default'
      modules: 'default'
